// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: protos/health.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId            string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DataSustainedInjury string `protobuf:"bytes,3,opt,name=data_sustained_injury,json=dataSustainedInjury,proto3" json:"data_sustained_injury,omitempty"`
	DateToBeHealed      string `protobuf:"bytes,4,opt,name=date_to_be_healed,json=dateToBeHealed,proto3" json:"date_to_be_healed,omitempty"`
	InjuryStatus        string `protobuf:"bytes,5,opt,name=injury_status,json=injuryStatus,proto3" json:"injury_status,omitempty"`
	HealthStatus        string `protobuf:"bytes,6,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
}

func (x *CreateHealthRequest) Reset() {
	*x = CreateHealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_health_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHealthRequest) ProtoMessage() {}

func (x *CreateHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_health_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHealthRequest.ProtoReflect.Descriptor instead.
func (*CreateHealthRequest) Descriptor() ([]byte, []int) {
	return file_protos_health_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHealthRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateHealthRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CreateHealthRequest) GetDataSustainedInjury() string {
	if x != nil {
		return x.DataSustainedInjury
	}
	return ""
}

func (x *CreateHealthRequest) GetDateToBeHealed() string {
	if x != nil {
		return x.DateToBeHealed
	}
	return ""
}

func (x *CreateHealthRequest) GetInjuryStatus() string {
	if x != nil {
		return x.InjuryStatus
	}
	return ""
}

func (x *CreateHealthRequest) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

type GetDateToBeFineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *GetDateToBeFineRequest) Reset() {
	*x = GetDateToBeFineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_health_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDateToBeFineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDateToBeFineRequest) ProtoMessage() {}

func (x *GetDateToBeFineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_health_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDateToBeFineRequest.ProtoReflect.Descriptor instead.
func (*GetDateToBeFineRequest) Descriptor() ([]byte, []int) {
	return file_protos_health_proto_rawDescGZIP(), []int{1}
}

func (x *GetDateToBeFineRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetDateToBeFineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateToBeHealed string `protobuf:"bytes,1,opt,name=date_to_be_healed,json=dateToBeHealed,proto3" json:"date_to_be_healed,omitempty"`
}

func (x *GetDateToBeFineResponse) Reset() {
	*x = GetDateToBeFineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_health_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDateToBeFineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDateToBeFineResponse) ProtoMessage() {}

func (x *GetDateToBeFineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_health_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDateToBeFineResponse.ProtoReflect.Descriptor instead.
func (*GetDateToBeFineResponse) Descriptor() ([]byte, []int) {
	return file_protos_health_proto_rawDescGZIP(), []int{2}
}

func (x *GetDateToBeFineResponse) GetDateToBeHealed() string {
	if x != nil {
		return x.DateToBeHealed
	}
	return ""
}

type UpdateHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId            string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DataSustainedInjury string `protobuf:"bytes,3,opt,name=data_sustained_injury,json=dataSustainedInjury,proto3" json:"data_sustained_injury,omitempty"`
	DateToBeHealed      string `protobuf:"bytes,4,opt,name=date_to_be_healed,json=dateToBeHealed,proto3" json:"date_to_be_healed,omitempty"`
	InjuryStatus        string `protobuf:"bytes,5,opt,name=injury_status,json=injuryStatus,proto3" json:"injury_status,omitempty"`
	HealthStatus        string `protobuf:"bytes,6,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
}

func (x *UpdateHealthRequest) Reset() {
	*x = UpdateHealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_health_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHealthRequest) ProtoMessage() {}

func (x *UpdateHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_health_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHealthRequest.ProtoReflect.Descriptor instead.
func (*UpdateHealthRequest) Descriptor() ([]byte, []int) {
	return file_protos_health_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateHealthRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *UpdateHealthRequest) GetDataSustainedInjury() string {
	if x != nil {
		return x.DataSustainedInjury
	}
	return ""
}

func (x *UpdateHealthRequest) GetDateToBeHealed() string {
	if x != nil {
		return x.DateToBeHealed
	}
	return ""
}

func (x *UpdateHealthRequest) GetInjuryStatus() string {
	if x != nil {
		return x.InjuryStatus
	}
	return ""
}

func (x *UpdateHealthRequest) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

type Health struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId            string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DataSustainedInjury string `protobuf:"bytes,3,opt,name=data_sustained_injury,json=dataSustainedInjury,proto3" json:"data_sustained_injury,omitempty"`
	DateToBeHealed      string `protobuf:"bytes,4,opt,name=date_to_be_healed,json=dateToBeHealed,proto3" json:"date_to_be_healed,omitempty"`
	InjuryStatus        string `protobuf:"bytes,5,opt,name=injury_status,json=injuryStatus,proto3" json:"injury_status,omitempty"`
	HealthStatus        string `protobuf:"bytes,6,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
}

func (x *Health) Reset() {
	*x = Health{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_health_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_protos_health_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_protos_health_proto_rawDescGZIP(), []int{4}
}

func (x *Health) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Health) GetDataSustainedInjury() string {
	if x != nil {
		return x.DataSustainedInjury
	}
	return ""
}

func (x *Health) GetDateToBeHealed() string {
	if x != nil {
		return x.DateToBeHealed
	}
	return ""
}

func (x *Health) GetInjuryStatus() string {
	if x != nil {
		return x.InjuryStatus
	}
	return ""
}

func (x *Health) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

type DeleteHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *DeleteHealthRequest) Reset() {
	*x = DeleteHealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_health_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHealthRequest) ProtoMessage() {}

func (x *DeleteHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_health_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHealthRequest.ProtoReflect.Descriptor instead.
func (*DeleteHealthRequest) Descriptor() ([]byte, []int) {
	return file_protos_health_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteHealthRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_health_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_health_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_health_proto_rawDescGZIP(), []int{6}
}

var File_protos_health_proto protoreflect.FileDescriptor

var file_protos_health_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0xeb, 0x01,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x75, 0x73, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x13, 0x64, 0x61, 0x74, 0x61, 0x53, 0x75, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64,
	0x49, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x6f, 0x5f, 0x62, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x42, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x65,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x35, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x42, 0x65, 0x46, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x44, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x42,
	0x65, 0x46, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a,
	0x11, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x62, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x6c,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x42, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x22, 0xdb, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32, 0x0a,
	0x15, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x75, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x5f,
	0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x64, 0x61,
	0x74, 0x61, 0x53, 0x75, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x6a, 0x75, 0x72,
	0x79, 0x12, 0x29, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x62, 0x65, 0x5f,
	0x68, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x42, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xce, 0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32,
	0x0a, 0x15, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x75, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64,
	0x5f, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x64,
	0x61, 0x74, 0x61, 0x53, 0x75, 0x73, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x6a, 0x75,
	0x72, 0x79, 0x12, 0x29, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x62, 0x65,
	0x5f, 0x68, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x6f, 0x42, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x32, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x32, 0x9d, 0x02, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x12, 0x3b, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0e, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x12, 0x55, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x42, 0x65,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x1e, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x42, 0x65, 0x46, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x42, 0x65, 0x46, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70,
	0x62, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_health_proto_rawDescOnce sync.Once
	file_protos_health_proto_rawDescData = file_protos_health_proto_rawDesc
)

func file_protos_health_proto_rawDescGZIP() []byte {
	file_protos_health_proto_rawDescOnce.Do(func() {
		file_protos_health_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_health_proto_rawDescData)
	})
	return file_protos_health_proto_rawDescData
}

var file_protos_health_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_health_proto_goTypes = []interface{}{
	(*CreateHealthRequest)(nil),     // 0: health.CreateHealthRequest
	(*GetDateToBeFineRequest)(nil),  // 1: health.GetDateToBeFineRequest
	(*GetDateToBeFineResponse)(nil), // 2: health.GetDateToBeFineResponse
	(*UpdateHealthRequest)(nil),     // 3: health.UpdateHealthRequest
	(*Health)(nil),                  // 4: health.Health
	(*DeleteHealthRequest)(nil),     // 5: health.DeleteHealthRequest
	(*Empty)(nil),                   // 6: health.Empty
}
var file_protos_health_proto_depIdxs = []int32{
	0, // 0: health.HealthServices.CreateHealth:input_type -> health.CreateHealthRequest
	3, // 1: health.HealthServices.UpdateHealth:input_type -> health.UpdateHealthRequest
	1, // 2: health.HealthServices.GetDateToBeHealthy:input_type -> health.GetDateToBeFineRequest
	5, // 3: health.HealthServices.DeleteHealth:input_type -> health.DeleteHealthRequest
	4, // 4: health.HealthServices.CreateHealth:output_type -> health.Health
	4, // 5: health.HealthServices.UpdateHealth:output_type -> health.Health
	2, // 6: health.HealthServices.GetDateToBeHealthy:output_type -> health.GetDateToBeFineResponse
	6, // 7: health.HealthServices.DeleteHealth:output_type -> health.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_health_proto_init() }
func file_protos_health_proto_init() {
	if File_protos_health_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_health_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_health_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDateToBeFineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_health_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDateToBeFineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_health_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_health_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Health); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_health_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_health_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_health_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_health_proto_goTypes,
		DependencyIndexes: file_protos_health_proto_depIdxs,
		MessageInfos:      file_protos_health_proto_msgTypes,
	}.Build()
	File_protos_health_proto = out.File
	file_protos_health_proto_rawDesc = nil
	file_protos_health_proto_goTypes = nil
	file_protos_health_proto_depIdxs = nil
}
